# Site settings
title: Fabio Fortini
email: fabio@fortini.dev
url: https://fortini.dev
description: "Fabio Fortini's personal website. Software Engineer, Product full-stack developer, Speaker."
keywords: "Software Engineer, Developer, Speaker"
skills: "Full Stack Developer - Speaker - XP enthusiast"
meta_author: Fabio Fortini

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Fabio Fortini
  location: Location
  social: Follow me on social networks
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/in/fabio-fortini
  - title: github
    url: https://github.com/FabioFortini

# Postal address (add as many lines as necessary)
# Not used
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
